-- 코드를 입력하세요
WITH TEMP AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT A.FOOD_TYPE, REST_ID, REST_NAME, A.FAVORITES FROM REST_INFO A JOIN TEMP B ON (A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.FAVORITES)
GROUP BY A.FOOD_TYPE
ORDER BY A.FOOD_TYPE DESC