WITH TMP AS (
    SELECT CAR_ID,
    CASE 
        WHEN START_DATE <= "2022-10-16" AND END_DATE >= "2022-10-16" THEN "대여중"
        ELSE "대여 가능" 
    END AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT A.CAR_ID, 
    CASE 
        WHEN "대여중" IN (SELECT DISTINCT AVAILABILITY FROM TMP WHERE CAR_ID = A.CAR_ID) THEN "대여중"
        ELSE "대여 가능"
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
GROUP BY A.CAR_ID
ORDER BY CAR_ID DESC;