-- 코드를 입력하세요
WITH FIRST_HALF_ORDER AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM FIRST_HALF
    GROUP BY FLAVOR
),
JULY_ORDER AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY
    GROUP BY FLAVOR
)

SELECT A.FLAVOR AS FLAVOR
FROM FIRST_HALF_ORDER A JOIN JULY_ORDER B ON A.FLAVOR = B.FLAVOR
ORDER BY A.TOTAL_ORDER + B.TOTAL_ORDER DESC
LIMIT 3