SELECT A.ID, A.GENOTYPE GENOTYPE, B.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA A INNER JOIN ECOLI_DATA B ON A.PARENT_ID = B.ID
WHERE A.PARENT_ID IS NOT NULL AND A.GENOTYPE & B.GENOTYPE = B.GENOTYPE
ORDER BY ID