-- 코드를 입력하세요
WITH TEMP AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT 
    GROUP BY CATEGORY
)
     
SELECT A.CATEGORY, PRICE, PRODUCT_NAME 
FROM FOOD_PRODUCT A JOIN TEMP B ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.MAX_PRICE
WHERE A.CATEGORY = '과자' OR A.CATEGORY = '국' OR A.CATEGORY = '김치' OR A.CATEGORY = '식용유'
ORDER BY PRICE DESC